baseURL = "https://gadamssonweb.github.io/"
languageCode = "en-us"
title = "G. Adamsson"
theme = "timer-hugo"
publishDir = "docs"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
#    [[menu.nav]]
#        name    = "About"
#        url     = "/about"
#        weight  = 2
#    [[menu.nav]]
#        name    = "Service"
#        url     = "/service"
#        weight  = 3
#    [[menu.nav]]
#       name    = "Gallery"
#       url     = "/gallery"
#       weight  = 4
#    [[menu.nav]]
#        name    = "Blog"
#        url     = "/blog"
#        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "We can deliver what you need to your space planning solution"
        description = "With many years of experience in the CET Designer platform"
        btn     = false
        btnText = "Download More"
        btnURL  = "https://themefisher.com/"
        [[params.banner.flipText]]
            title   = "Project Management"
        [[params.banner.flipText]]
            title   = "Development"
        [[params.banner.flipText]]
            title   = "Developer Training & Mentorship"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT THE COMPANY"
        content = "The company was founded 2018, by Gustav Adamsson in Link√∂ping, Sweden. Starting up the company Gustav had many years of experience working as a Project Manager & Programmer in the CET Designer platform."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK?"
        content = "We are always open for discussing opportunities.\nContact us at gustav@gadamsson.com or click the button below if you want to know more."
        btnText = "Contact us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Feature Product Section
    [params.featureProduct]
        enable  = false
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    